### ISSUE TITLE
Module Fails During Import

### ISSUE THREAD

**Issue by MontelAle** [Cuadrix/puppeteer-page-proxy#10]
The module fails during import. There is a problem with the got library.

```
got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
```

You can reproduce this with the first example script in this repo readme.

**Comment by Bouzazi** [comment]
I use [esm](https://www.npmjs.com/package/esm) and it works just fine.
`node -r esm main.js`

**Comment by Cuadrix** [comment]
Works fine for me.
If it's a problem with Got, then I can do nothing about it.
You'll need to open an issue there.
