### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by Bouzazi** [Cuadrix/puppeteer-page-proxy#12]
I'm having trouble with HTTPS.
Works fine and I'm getting to use a separate proxy for each page but It is redirecting to HTTP.

**Comment by valiant1x** [comment]
@Cuadrix HTTPS broken for me as well.

**Comment by smartdev10** [comment]
any updates about this?

**Comment by Cuadrix** [comment]
Updated to v1.2.4
Read about it [here](https://github.com/Cuadrix/puppeteer-page-proxy#faq)
