### ISSUE TITLE
I can't get this to work with example code

### ISSUE THREAD

**Issue by notasgoodasyou** [Cuadrix/puppeteer-page-proxy#14]
```
const puppeteer = require('puppeteer');
const useProxy = require('puppeteer-page-proxy');

(async () => {
    const site = 'https://www.test.com';
    const proxy = 'https://proxy_ip:port';

    const browser = await puppeteer.launch({
      headless: true,
      ignoreHTTPSErrors: true,
      args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-web-security'
      ]});

    const page = await browser.newPage();
    await useProxy(page, proxy);
    await page.goto(site);
})();
```

Is something wrong with my code above? I keep getting ERR_FAILED after using useProxy() it gives this error below. If I remove `await useProxy(page, proxy);` then it works again but without proxy.

`UnhandledPromiseRejectionWarning: Error: net::ERR_FAILED at https://www.test.com`

**Comment by DmitryKvant** [comment]
Try use http://proxy_ip:port
It help for me

**Comment by acrogenesis** [comment]
I'm also having trouble with a very similar code. Using `this.args.push("--proxy-server=127.0.0.1:8888")` works but not `await useProxy(this.page, "127.0.0.1:8888")` with or without `http://`.

**Comment by Cuadrix** [comment]
Updated it. Try 1.2.4

**Comment by AneeshQuonain** [comment]
I am still getting same error with this can you help me please

**Comment by makanSukros** [comment]
Still same result, getting hang response
