### ISSUE TITLE
Error if page redirection

### ISSUE THREAD

**Issue by Hodor228** [Cuadrix/puppeteer-page-proxy#17]
Hi, i have an error if page have redirection to another url:
await useProxy(page, proxy)
await page.goto(`https://accounts.ea.com/connect/auth?locale=en_US&state=bf4&redirect_uri=https%3A%2F%2Fbattlelog.battlefield.com%2Fsso%2F%3Ftokentype%3Dcode&response_type=code&client_id=battlelog&display=web%2Flogin`)

(node:20464) UnhandledPromiseRejectionWarning: Error: net::ERR_TOO_MANY_REDIRECTS at https://accounts.ea.com/connect/auth?locale=en_US&state=bf4&redirect_uri=https%3A%2F%2Fbattlelog.battlefield.com%2Fsso%2F%3Ftokentype%3Dcode&response_type=code&client_id=battlelog&display=web%2Flogin

**Comment by Cuadrix** [comment]
Try the latest version.
