### ISSUE TITLE
NordVPN Proxy and Netflix

### ISSUE THREAD

**Issue by mckraemer** [Cuadrix/puppeteer-page-proxy#20]
Hi, you closed the other issue, it still doensn't work for me and never worked for me before. 
I am trying to use this module with a NordVPN socks5 proxy. I can visit the login page without any issues. My Problem is when I enter the credentials and press login I get the error: (failed)net::ERR_FAILED
Only the login fails for me.
The socks5 connection seems to work as ipleak.net gives me the proxy ip.
When I use the normal VPN client it works without any issues.

```
const puppeteer = require('puppeteer');
const useProxy = require('puppeteer-page-proxy');


const browser = await puppeteer.launch({
        headless: config.headless
    })  
const page = await browser.newPage();
await useProxy(page, 'socks5://${vpnusername}:${vpnpassword}@de550.nordvpn.com:1080')

await page.goto('https://www.netflix.com/en/Login')
```

**Comment by Cuadrix** [comment]
So it only happens after submitting the login details in the page?
Does it happen elsewhere?
What node, chrome and puppeteer versions are you using?

**Comment by mckraemer** [comment]
Yes it only happens after submitting the login details.
I have only tried it with Netflix, can try it with Tidal later.
Puppeteer: 3.1.0
Node: 12.17.0
Chromium: 83.0.4103.0

**Comment by mckraemer** [comment]
Can't login to tidal either because I can't finish the recaptach. No idea why.

**Comment by Cuadrix** [comment]
This must be an issue with the requests. Something with missing headers or perhaps form data not being sent properly. I'll see what I can do

**Comment by t1nky** [comment]
Same error using proxy and trying to access instagram. 
```
(node:11788) UnhandledPromiseRejectionWarning: ReadError: The server aborted the pending request
Error: net::ERR_FAILED at https://www.instagram.com/
```
Using http proxy with authentication:
1) Use puppeteer-page-proxy -- results in an error
2) Use same proxy directly in Windows or Android -- OK
3) Use another proxy in puppeteer-page-proxy -- OK
All proxies I am using are HTTP(s).

**Comment by Cuadrix** [comment]
Updated. Try and see if the issue persists on [1.2.6](https://github.com/Cuadrix/puppeteer-page-proxy/releases/tag/1.2.6)
