### ISSUE TITLE
Intereception detected

### ISSUE THREAD

**Issue by ordimans** [Cuadrix/puppeteer-page-proxy#21]
Hello

Thanks you for your module.
It work very well to use Socks5 with Auth.

But i have a problem on my bot, it is detected by the website when i use the interception.

I tried without, with my IP and it's OK, but with interception, the new account is KO.

Do you have an idea ?

**Comment by Cuadrix** [comment]
Which website is this?
What happens if you use the interception without the proxy? E.g:
```js
await page.setRequestInterception(true);
page.on('request', req => {
    req.continue();
});
await page.goto(site);
```

**Comment by ordimans** [comment]
It's aliexpress.
It's same with this code.
Account registered is anormal....

I am using StealthPlugin but not sure if it's ok...
Haireline is missing. i will check on the git.

But if you have some ideas, i can try.
