### ISSUE TITLE
page.listeners is not a function

### ISSUE THREAD

**Issue by LucasLundJensen** [Cuadrix/puppeteer-page-proxy#22]
I get the following error trying to use page-proxy with the latest version of puppeteer (3.2.0)
Node version: 12.13.1
Chrome version:  83.0.4103.61
`(node:17016) UnhandledPromiseRejectionWarning: TypeError: page.listeners is not a function
    at removeRequestListener (E:\Developement Projects\Web Applications\osrsac\server\node_modules\puppeteer-page-proxy\src\core\proxy.js:36:32)
    at useProxy (E:\Developement Projects\Web Applications\osrsac\server\node_modules\puppeteer-page-proxy\src\core\proxy.js:56:9)
    at async E:\Developement Projects\Web Applications\osrsac\server\index.js:86:9`

I haven't done anything but follow the examples, I do use Authentication with the proxy tho, if that makes any difference.

**Comment by Cuadrix** [comment]
Yeah, this is because of the update.
I will update it for puppeteer 3.2.0 shortly

**Comment by LucasLundJensen** [comment]
Ah alright, awesome!

**Comment by Cuadrix** [comment]
This is an issue with puppeteer itself.
They recently swapped the EventEmitter for [Mitt](https://github.com/developit/mitt), which caused issues.

_https://github.com/puppeteer/puppeteer/issues/5944#issuecomment-636121949_

As stated in the comment above, this module will stick with 3.1.0 until the issue has been resolved.

**Comment by Cuadrix** [comment]
Updated and fixed in [1.2.6](https://github.com/Cuadrix/puppeteer-page-proxy/releases/tag/1.2.6)
