### ISSUE TITLE
how to set header ?

### ISSUE THREAD

**Issue by hulubo** [Cuadrix/puppeteer-page-proxy#25]
```
newPage.on('request', async request => {
      if (!request.isNavigationRequest()) {
        request.continue();
        return;
      }

      const headers = request.headers();
      headers['user-agent'] = 'Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Mobile Safari/537.36';
      await useProxy(request, { proxy, headers });
    });

await newPage.goto(url)
```
this ok ?

**Comment by shubhamR1997** [comment]
if you are talking about specfically for userAgent then puppeeter provides setUserAgent method where you can define your user-agent. so you can use  It  like this
  await page.setUserAgent('Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Mobile Safari/537.36");

**Comment by Cuadrix** [comment]
That should be right
