### ISSUE TITLE
Cache Access Denied

### ISSUE THREAD

**Issue by thebobthebob** [Cuadrix/puppeteer-page-proxy#29]
`const page = await browser.newPage();

    await useProxy(page, 'https://power-fr.tlsext.com:10799');
    await page.goto('https://google.com', {
        waitUntil: 'domcontentloaded',
    })
`

When I open the page,it shows below wrong message:
Cach Access Denied
The following error was encountered while trying to retrieve the URL: https://google.com/*
Cache Access Denied.
Sorry, you are not currently allowed to request https://google.com/* from this cache until you have authenticated yourself.
Please contact the cache administrator if you have difficulties authenticating yourself.

[Problem Screenshot](https://i.imgur.com/bUNeNYr.png)

How do I solve this problem?

Thank you.

**Comment by 3024407779** [comment]
Do you have a way to set up all page IPs? I need to get all page proxies
