### ISSUE TITLE
I don't think it is working

### ISSUE THREAD

**Issue by elpaxel** [Cuadrix/puppeteer-page-proxy#3]
Sorry your library is working but you need to add to readme that page.authenticate not working but proxy like http(s)://login:pass@ip:port WORKS

**Comment by elpaxel** [comment]
Soooo now I see that it is working like this:
http proxy + http website = good
http proxy + https website = not working
https proxy + https website = good
https proxy + http website = good
But page.authenticate not working at all.
And when I'm trying puppeteer.connect instead puppeteer.launch it's not even trying to use proxy because apify returns my real IP.

**Comment by Cuadrix** [comment]
> http proxy + https website = not working

That's strange. It works fine for me

> And when I'm trying puppeteer.connect instead puppeteer.launch it's not even trying to use proxy

The below works:
```js
(async () => {
    let site = 'https://ipleak.net';
    const browserURL = 'http://127.0.0.1:21222';
    await puppeteer.launch({
        args: [
            "--remote-debugging-port=21222"
        ],
        headless: false,
    });
    const browser = await puppeteer.connect({browserURL});
    const page = await browser.newPage();
    await useProxy(page, "http://163.172.189.32:8811");
        let data = await useProxy.lookup(page);
        console.log(data.ip);
    page.goto(site);
})();
```

> page.authenticate not working but proxy like http(s)://login:pass@ip:port WORKS

Thanks! I will add it to the README

**Comment by elpaxel** [comment]
Can you test one more thing please. I'm using browserify and it seems that there library is not working. Simple `index_dev.js`:
```
var puppeteer = require('puppeteer');
var useProxy = require('puppeteer-page-proxy');

(async () => {
  var browser = await puppeteer.connect({browserURL});
  var context = await browser.createIncognitoBrowserContext();
  var page = await context.newPage();
  await useProxy(page, "...");
  await page.goto("https://api.ipify.org");
})();
```
Then in `node_modules/puppeteer` create folder `utils` and inside `utils` create `browser` folder. And then put [WebSocket.js](https://github.com/puppeteer/puppeteer/blob/master/utils/browser/WebSocket.js) file inside `browser` folder.
Finally `browserify index_dev.js -o index.js`

**Comment by Cuadrix** [comment]
What's the result you are expecting?
It does get bundled if that's what you are after

**Comment by elpaxel** [comment]
Yeah it is successfully get bundled but it is not working :) I mean same code on server side is working and inside browser is not working.

**Comment by Cuadrix** [comment]
That's because the library isn't meant to be used directly inside a browser. The code used in the library is from the [puppeteer API](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md), which is exclusively node.js

**Comment by elpaxel** [comment]
Are you sure ? Because this [Bundling For Web Browsers](https://github.com/puppeteer/puppeteer/tree/master/utils/browser) is official and working. I think there is all the puppeteer API supported. And snippet that I've posted above successfully connects to the instance, successfully creates incognito window and successfully opens new tab and finally successfully go to the Apify. BUT useproxy not working, Apify returns my real IP. And there is no errors at all.

**Comment by Cuadrix** [comment]
Seems like you'll have to debug and see
Add a bunch of `console.logs` and in the `puppeteer-page-proxy.js` or something to see if the function executes.
The first function below the class is the main function.
I can't test it out now because I'm busy

**Comment by elpaxel** [comment]
So basically problem in the request library itself. Browserify'ed version of it doesn't support proxy. Because I believe proxy inside request library is separated (dynamically required or something). I tried to replace request library with few alternatives but didn't succeed. So I know that is not problem of your library but I will appreciate any help.

**Comment by elpaxel** [comment]
Nevermind I successfully replaced request with axios and stalled by "refused to set unsafe header" errors. So I think it is impossible to make requests interception inside browser.
