### ISSUE TITLE
TimeoutError: Navigation timeout of 60000 ms exceeded

### ISSUE THREAD

**Issue by kornflex** [Cuadrix/puppeteer-page-proxy#30]
Hello,

I'm using puppeteer-extra-plugin-proxy with HTTP proxies.

But I have now SOCKS5 proxies so I have to change the module because he doesn't work with SOCKS.

That's why I'm here ;)

With this module, I have this error : TimeoutError: Navigation timeout of 60000 ms exceeded
( I increase the default timeout )
for http et socks proxies.

The timeout is coming when I execute : await page.goto(url);

All log : 
```
TimeoutError: Navigation timeout of 60000 ms exceeded
    at /var/www/clients/client1/web13/web/v2/node_modules/puppeteer/lib/cjs/common/LifecycleWatcher.js:101:111
    at async FrameManager.navigateFrame (/var/www/clients/client1/web13/web/v2/node_modules/puppeteer/lib/cjs/common/FrameManager.js:71:21)
    at async Frame.goto (/var/www/clients/client1/web13/web/v2/node_modules/puppeteer/lib/cjs/common/FrameManager.js:296:16)
    at async Page.goto (/var/www/clients/client1/web13/web/v2/node_modules/puppeteer/lib/cjs/common/Page.js:749:16)
    at async /var/www/clients/client1/web13/web/v2/7-params.js:69:3
 ```

Thank you for your help

**Comment by Cuadrix** [comment]
Does the problem still occur?
Could you test more proxies and try to reproduce the issue?
This is most likely an issue with the proxy itself.

**Comment by kornflex** [comment]
Hello,

I'm still stuck with this error... 
I'm using trial proxies. It works great with my old script and puppeteer-extra-plugin-proxy

I've bought privateinternetaccess proxy (socks5) to try : still the same error.

So, with PIA proxy and trial proxies from webshare.io, same issue :/
But trial proxies from webshare.io works great with my old proxy.

I understand that this can happen with poor quality of proxy but with trial version it works great :/

**Comment by Fmstrat** [comment]
Perhaps this may be site specific. We are seeing this in the implementation of https://github.com/jef/streetmerchant/issues/1766 in Streetmerchant, too. Perhaps there is code there that will help identify the source?

It seems to work fine for most sites, but others it consistently throws the error even with a SOCKS5 SSH proxy to localhost.

Could also be related to https://github.com/jef/streetmerchant/issues/1844 as both of those issues stem from how this library is implemented.
