### ISSUE TITLE
Issue with using the code

### ISSUE THREAD

**Issue by jackwicklow1** [Cuadrix/puppeteer-page-proxy#31]
Hi there. I am using puppeteer, and want to link it to an existing chrome browser which initialises through chrome-launcher. The only way I could find to change a proxy through puppeteer was through puppeteer-page-proxy. However, I am struggling to change the proxy. My code just now where I use the puppeteer-page-proxy code is as follows:

await page.setRequestInterception(true);

page.on('request', async request => {
    await useProxy(request, "34.205.165.62:3112");
});

const proxy = 'myuser:mypass@34.205.165.62:3112';

await page.goto(URL);

But it does not work. I have tested, and when I change the proxy to null it works, so I am doing something wrong. Please could someone help me.

**Comment by Cuadrix** [comment]
Look at the [API](https://github.com/Cuadrix/puppeteer-page-proxy#api) section of readme.md:
> - `proxy` <[string](https://developer.mozilla.org/en-US/docs/Glossary/String)|[object](https://developer.mozilla.org/en-US/docs/Glossary/Object)> Proxy to use in the current page.
>   * Begins with a protocol (e.g. http://, https://, socks://)

You did not include the protocol in your proxy string.
If your proxy is a http one, then you add `http://` in the beginning of the proxy string, like this:
`http://34.205.165.62:3112`

Similarly if it's a socks proxy, you add the `socks://` prefix instead, like this:
`socks://34.205.165.62:3112`

Proxies with authentication are no exception:
Assuming http proxy:
`http://myuser:mypass@34.205.165.62:3112`

Also about this; `const proxy = 'myuser:mypass@34.205.165.62:3112';`:
Besides it lacking the protocol aswell, this variable is not even being used.
