### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by Kikey-y** [Cuadrix/puppeteer-page-proxy#34]
Hello, I'm trying to run this very basic piece of code but I'm always getting the error above `TypeError: Cannot read property 'get' of undefined`, at the useProxy line. What's the problem here???
`(async () => {
    const browser = await puppeteer.launch({headless: false});
    var page = await browser.newPage();
    const proxy = 'http://user:pass@host:port'
    await useProxy(page, proxy)
    await page.goto('http://api.myip.com');
    await browser.close();
})();
`

**Comment by Cuadrix** [comment]
This package used a method that was removed in [v4.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v4.0.0)
Update Puppeteer to the latest version.

**Comment by smashah** [comment]
@Cuadrix how would updating to the latest version of puppeteer fix this issue if the functionality was removed in v4.0.0?

**Comment by Cuadrix** [comment]
@smashah Because now the package uses a different method which is not available in pre v4.0.0's exposed methods.

**Comment by smashah** [comment]
@Cuadrix I don't think it is working any more in 5.2.1
