### ISSUE TITLE
Some websites result in "Brotli is not supported on Node.js < 12" error

### ISSUE THREAD

**Issue by smashah** [Cuadrix/puppeteer-page-proxy#37]
Maybe add a minimum node version badge?

**Comment by Cuadrix** [comment]
Could you share some of the websites that cause that error to be thrown?

**Comment by smashah** [comment]
https://web.whatsapp.com

You'll need to log this error https://github.com/Cuadrix/puppeteer-page-proxy/blob/7bcdb82f33cdbf7da17908475a2765e25cf55c55/src/core/proxy.js#L40
