### ISSUE TITLE
Reuse exists cookies

### ISSUE THREAD

**Issue by exhum4n** [Cuadrix/puppeteer-page-proxy#38]
How i can reuse cookies with this module?

after authorization i did try get page.cookies(URL) to get authorized cookies, but this cookies is wrong. then i remove string with useProxy i receive good cookies that work well. How can i resolve this?

**Comment by exhum4n** [comment]
and https not working too

**Comment by Cuadrix** [comment]
https://github.com/Cuadrix/puppeteer-page-proxy/issues/69#issuecomment-1273020411
