### ISSUE TITLE
consider rewriting using got

### ISSUE THREAD

**Issue by gajus** [Cuadrix/puppeteer-page-proxy#4]
Currently `puppeteer-page-proxy` depends on `request`, which in turns installs `tunnel-agent@0.6.0`. The latter patches the global `http.Agent` in a way that breaks many HTTP requests in latest Node.js. Considering that `request` is deprecated`, got is a safer alternative.

**Comment by gajus** [comment]
I couldn't figure out the mess in the current database.

Consider contributing to https://github.com/gajus/puppeteer-proxy.

**Comment by Cuadrix** [comment]
Thanks. I wasn't aware of that. I'll recode it using Got

**Comment by gajus** [comment]
By now you can just use pupepteer-proxy.
