### ISSUE TITLE
useProxy per page with setRequestInterception in my code raises an error  `Request is already handled!`

### ISSUE THREAD

**Issue by chapov** [Cuadrix/puppeteer-page-proxy#46]
subj.

How to get around this?

```js
    const domainsBL = [
         "domain.com",
         "dname.net"
    ]
    page.on('request', interceptedRequest => {
        browser.countRequests++;

        const reqDomain = new URL( interceptedRequest.url() ).host;
        let requestBlocked = false;

        if ( domainsBL ) {
            if ( domainsBL.includes( reqDomain ) ) {
                interceptedRequest.abort();
                requestBlocked = true;
            }
        }
        if ( !requestBlocked ) {
            interceptedRequest.continue();
        }
    });
    ...
    ...
    const proxy = utils.getProxy( );

    await useProxy( page, proxyAddress);
    await page.goto( data.url );
          
```

`
(node:42) UnhandledPromiseRejectionWarning: Error: Request is already handled!
at Object.exports.assert (/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
at HTTPRequest.abort (/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:314:21)
at requestHandler (/usr/src/app/node_modules/puppeteer-page-proxy/src/core/proxy.js:41:23)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:42) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:42) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by jayant-dhawan** [comment]
I'm also facing this issue. How did you resolve this?

**Comment by 3024407779** [comment]
Do you have a way to set up all page IPs? I need to get all page proxies

**Comment by bgkoala** [comment]
I had the same in my project. I was using a pool of pages to execute individual tasks. The problem is that I define a new request listener (page.on('request', ...) every time a new task was executed with removing the listener from the previous task. 

I added the following at the end of a task:
`page.removeAllListeners('request');`

**Comment by sharifpour** [comment]
puppeteer-page-proxy module intercepts the request on its core (page.on('request')) and you're also trying to intercept the request in your app. This causes conflicts and it gives the error that you got.
You need to use the proxy like this:
```
await page.setRequestInterception(true);
page.on('request', async request => {
    //your code

    await useProxy(request, proxyAddress);
});
