### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Nisthar** [Cuadrix/puppeteer-page-proxy#53]
I used your example code with proxies from http://free-proxy.cz/en/

![ice_screenshot_20201125-124928](https://user-images.githubusercontent.com/11994157/100195066-cffd3600-2f1c-11eb-800a-8ca9fe0a793b.png)

All other tabs work correctly.

**Comment by pkmnmstr98** [comment]
Show us some code please lol

**Comment by CedricBrandt** [comment]
Also experiencing this for HTTPS traffic only. Any workaround for this?

**Comment by CedricBrandt** [comment]
For me this was occuring because I used an outdated version of HttpsProxyAgent in the same project. After npm update it was fixed for me

**Comment by Maxou44** [comment]
I had the same error, when we use a HTTPS proxy, we should use the domain name as host, we can't use an IP address or the security handshake with the proxy will fail.

https://myuser:mypassword@123.123.123.123:443 => Will fail
https://myuser:mypassword@serv1.myproxydomain.com:443 => Will succeed

Maybe it could be nice to add this information in the README?

**Comment by pkmnmstr98** [comment]
https://github.com/TooTallNate/node-https-proxy-agent/issues/12

**Comment by 3024407779** [comment]
Do you have a way to set up all page IPs? I need to get all page proxies

**Comment by CedricBrandt** [comment]
@3024407779 you can set the proxy for the whole puppeteer instance via chromes launch parameters

**Comment by mhombach** [comment]
> I had the same error, when we use a HTTPS proxy, we should use the domain name as host, we can't use an IP address or the security handshake with the proxy will fail.
> 
> https://myuser:mypassword@123.123.123.123:443 => Will fail
> https://myuser:mypassword@serv1.myproxydomain.com:443 => Will succeed
> 
> Maybe it could be nice to add this information in the README?

I think this is not the issue. You can, without any problems, start Chrome(Chromium with the proxy-parameter and assign a proxy for HTTPS by providing the IP only. So this has to work. I am getting the same error though, would love to get this fixed.
