### ISSUE TITLE
TOR/onion Support not working

### ISSUE THREAD

**Issue by lesleyxyz** [Cuadrix/puppeteer-page-proxy#60]
I enabled TOR's proxy feature using:
https://stackoverflow.com/questions/55497125/how-to-configure-a-tor-proxy-on-windows

Now when I use puppeteer-page-proxy, my IP get changed successfully of one of the TOR network.
Though when I navigate to an .onion URL it says ERR_FAILED.
Normal HTTP/HTTPS goes through the TOR proxy.

When I supply the TOR proxy as argument ("args": [ "--proxy-server=socks5://127.0.0.1:9051" ]) it does work.
Anyone has an idea? Or atleast an idea on how to make this working in this code base?

Thank you!

**Comment by riabikov** [comment]
Try like this:
`await useProxy(page, 'socks://127.0.0.1:9051');`
If you specify the version of **socks**, then it does not work for me either:
`await useProxy(page, 'socks5://127.0.0.1:9051');`
