### ISSUE TITLE
when visit a url with port it cannot work

### ISSUE THREAD

**Issue by mlboy** [Cuadrix/puppeteer-page-proxy#61]
```
page.on('request', async request => {
    await useProxy(request, proxyURL)
 })
```

when the url has "port" not 80, it cannot work

such as:

http://www.test.com:8181/jquery/jquery-1.7.1.min.js?v=20140716

the port  is 8181 ,but get resquest is :
http://www.test.com/jquery/jquery-1.7.1.min.js?v=20140716

**Comment by Cuadrix** [comment]
fixed in v1.2.9, thanks for contributing
