### ISSUE TITLE
Not working with latest Puppeteer versions

### ISSUE THREAD

**Issue by smashah** [Cuadrix/puppeteer-page-proxy#78]
The `request._client` property is now private resulting in the following error:

```js
return (await client.send("Network.getCookies", urls)).cookies;
TypeError: Cannot read properties of undefined (reading 'send')
```

https://github.com/open-wa/wa-automate-nodejs/issues/2755

**Comment by smashah** [comment]
Latest versions expose the private client via a method:

https://github.com/puppeteer/puppeteer/pull/8556/files

This should work:

```js
return (await client().send("Network.getCookies", urls)).cookies;
```

**Comment by smashah** [comment]
I have submitted PR #79 

Please review and release a new version as a lot of people are relying on this library.

Thanks

**Comment by vanxv** [comment]
> I have submitted PR #79
> 
> Please review and release a new version as a lot of people are relying on this library.
> 
> Thanks

can run?

**Comment by nickmurr** [comment]
Having the same issue. Any way to fix it?

**Comment by MohamadKh75** [comment]
Any updates?
cc @Cuadrix

**Comment by Himly1** [comment]
Same issue here any updates ?
```
"dependencies": {
    "puppeteer": "^16.1.0",
    "puppeteer-page-proxy": "^1.2.8",
  }
```

**Comment by smashah** [comment]
@Himly1 
https://github.com/Cuadrix/puppeteer-page-proxy/pull/79#issuecomment-1233477307

**Comment by Himly1** [comment]
@smashah 
Thanks!

**Comment by jan** [comment]
Current master works for me with latest merge.

**Comment by nuthinking** [comment]
Not working for me with latest.
