### ISSUE TITLE
Does not work on some sites like twitter

### ISSUE THREAD

**Issue by 0xuhe** [Cuadrix/puppeteer-page-proxy#87]
I tried use this plugin for twitter, but fails, and got `Error: net::ERR_FAILED at https://twitter.com`

It works fine if I launch with arg '--proxy-server=http://proxy'

**Comment by 0xuhe** [comment]
my mistake, fixed it

**Comment by everleek** [comment]
I also found that this error `Error: net::ERR_FAILED at` occurs frequently

**Comment by everleek** [comment]
> my mistake, fixed it

how fixed it ?

**Comment by 0xuhe** [comment]
@abbo 
This plugin fetch the page content by nodejs first, then render it in puppeteer.
You should make sure that the running script could visit your destination through proxy.

**Comment by abbo** [comment]
@0xuhe 
Got it, tks

**Comment by parvinders347** [comment]
> @abbo This plugin fetch the page content by nodejs first, then render it in puppeteer. You should make sure that the running script could visit your destination through proxy.

what does it mean?
