### ISSUE TITLE
Attempting to use proxy per page gives off an error [ TypeError: useProxyPer[target.constructor.name] is not a function ]

### ISSUE THREAD

**Issue by hishamw** [Cuadrix/puppeteer-page-proxy#98]
Following the documentation when attempting to use proxy per page i am getting the below error ... 

TypeError: useProxyPer[target.constructor.name] is not a function

    "puppeteer": "^14.1.0",
    "puppeteer-page-proxy": "^1.3.0",

**Comment by CursedMun** [comment]
Did you manage to find a solution?

**Comment by JonathanLehner** [comment]
no solution?

**Comment by senzacionale** [comment]
Same problem here after update puppeteer to latest version

**Comment by oliveremberton** [comment]
This doesn't appear to be fixed to me, same problem in Puppeteer 21.3.x but not in 21.2.x.

**Comment by senzacionale** [comment]
Any update?

**Comment by LeM0-Dev** [comment]
@senzacionale fixed here if you need: https://github.com/LeM0-Dev/puppeteer-page-proxy

**Comment by noname29** [comment]
@LeM0-Dev and which one is the fix ?

**Comment by noname29** [comment]
I installed it using ```npm i @lem0-packages/puppeteer-page-proxy``` yet it says ```Cannot find module puppeteer-page-proxy``` @LeM0-Dev
